name = "klaverjassen-stats"
main = "src/index.js"
compatibility_date = "2024-09-01"

# Vul na het aanmaken van de KV-namespace de id hieronder in:
#   wrangler kv namespace create STATS
[[kv_namespaces]]
binding = "STATS"
id = "08bd0cf5713042bca6f439d71bb44757"
